const winchaingroupApi = "http://47.104.95.206:8010/";


module.exports = {
    //登录
    uesrRegister: winchaingroupApi + 'users/v1/login/',//实验室管理员接口(1)登录
    getLaboratory_topNumber: winchaingroupApi + 'ex/app1/top/',//百分比(12)
    getAbilityintroduce: winchaingroupApi + 'sys/app1/sysintroduce/',//实验室能力介绍(3)
    getSystem_info: winchaingroupApi + 'sys/app1/sysmsg/',//实验室公告栏列表(7)
    updataFile: winchaingroupApi + 'sys/v1/file/',//文件上传
    setSystem_userinfo: winchaingroupApi + 'users/app1/userinfo/',//设置(214)
    getSystem_msg: winchaingroupApi + 'sys/app1/msg/',//通知 (4)
    getSystem_msgnum: winchaingroupApi + 'sys/app1/msgnum/',// 通知数量 (13)
    setSystem_msgnum: winchaingroupApi + 'sys/app1/msg/',//通知修改(14)
    deleteSystem_msgnum: winchaingroupApi + 'sys/app1/msg/',//通知删除(15)
    /**@name 实验室管理员 */
    getLabmanage_systemNumber: winchaingroupApi + 'ex/app1/num/',// 项目分配 审核个数(16)
    //任务分配
    getLabmanage_project : winchaingroupApi + 'ex/app1/project1/',//项目列表(5)
    getLabmanage_projectDetailList: winchaingroupApi + 'ex/app1/project1/',//项目详情 试验列表(6)
    getLabmanage_projectEngineerList: winchaingroupApi + 'users/app1/user1/?role=5',//试验工程师列表(8)
    allocationLabmanage_projectLeader: winchaingroupApi + 'ex/app1/project1/',// 项目试验工程师分配
    getLabmanage_materialEngineerList: winchaingroupApi + 'users/app1/user1/?role=8',//物料工程师列表(9)
    allocationLabmanage_EngineerList: winchaingroupApi +'ex/app1/experiment1/',//分配(10)
    //管理事项
    getLabmange_userList: winchaingroupApi+ 'users/app1/user',//人员列表(2)
    getLabmanage_equipmentList: winchaingroupApi + 'eq/app1/equipment1/',//设备管理列表(38)
    getLabmanage_equipmentDetail: winchaingroupApi + 'eq/app1/equipment1/',//设备详情 (39)
    getLabmanage_upkeeprecord: winchaingroupApi + 'eq/app1/upkeeprecord1/?equipment=',//保养记录列表 (42)
    getLabmanage_maintainrecord: winchaingroupApi + 'eq/app1/maintainrecord1/?equipment=',//维修记录列表(41)
    getLabmanage_meterecord: winchaingroupApi + 'eq/app1/meterecord/?equipment=',//计量记录列表(40)
    getLabmanage_standardList: winchaingroupApi + 'sys/app1/standard/',//试验标准列表 (44)
    getLabmanage_testwaymanageList: winchaingroupApi + 'sys/app1/testwaymanage/',//试验方法列表(43)
    getLabmanage_finishprojectList: winchaingroupApi + 'ex/app1/finishproject1/',//历史项目列表(46)
    getLabmanage_finishprojectDetail: winchaingroupApi + 'ex/app1/finishproject1/',// 项目详情(47)
    getLabmanage_frockList: winchaingroupApi + 'eq/app1/frock1/',//工装列表(45)
    //任务审核
    getLabmanage_projectreportList: winchaingroupApi + 'ex/app1/projectreport/',//项目报告未审核列表 (17)\
    getLabmanage_projectreportDetail: winchaingroupApi + 'ex/app1/projectreport/',//项目报告详情(18)
    getLabmanage_meteringList: winchaingroupApi + 'eq/app1/metering1/',//计量申请列表(20)
    getLabmanage_meteringDetail: winchaingroupApi + 'eq/app1/metering1/',//计量申请详情 (21)
    setLabmanage_meteringDetail: winchaingroupApi + 'eq/app1/metering1/',//计量申请审核(22)
    getLabmanage_material_application: winchaingroupApi + 'eq/app1/material_application1/',// 物料申请列表(23)
    getLabmanage_material_applicationDetail: winchaingroupApi + 'eq/app1/material_application1/',//物料申请详情(24)
    setLabmanage_material_applicationDetail: winchaingroupApi + 'eq/app1/material_application1/',//物料申请审核 (25)
    getLabmanage_applicationList: winchaingroupApi + 'eq/app1/application1/',//设备申请列表(26)
    getLabmanage_applicationDetail: winchaingroupApi + 'eq/app1/application1/',//设备申请详情(27)
    setLabmanage_applicationDetail: winchaingroupApi + 'eq/app1/application1/',//设备申请审批(28)
    getLabmanage_ondutyList: winchaingroupApi + 'sys/app1/onduty1/',//值班申请列表 (29)
    getLabmanage_ondutyDetail: winchaingroupApi + 'sys/app1/onduty1/',//值班申请详情(30)
    setLabmanage_ondutyDetail: winchaingroupApi + 'sys/app1/onduty1/',//值班申请审核(31)
    getLabmanage_testwayList: winchaingroupApi + 'sys/app1/testway1/',//试验方法待审核列表(32)
    getLabmanage_testwayDetail: winchaingroupApi + 'sys/app1/testway1/',//试验方法详情 (33)
    setLabmanage_testwayDetail: winchaingroupApi + 'sys/app1/testway1/',//试验方法审核(34)
    getLabmanage_frockapplyList: winchaingroupApi + 'eq/app1/frockapply1/',//工装申请列表(35)
    getLabmanage_frockapplyDetail: winchaingroupApi + 'eq/app1/frockapply1/',//工装申请详情(36)
    setLabmanage_frockapplyDetail: winchaingroupApi + 'eq/app1/frockapply1/',//工装申请审批
    sendLabmanage_systremMsg: winchaingroupApi + 'sys/v1/sysmsg/',//实验室公告栏创建(48)

    /**@name 物料管理员 */
    getMaterialEngineer_systemNumber: winchaingroupApi + 'ex/app1/top8/',//顶部数字统计(821)
    getMaterialEngineer_materielList: winchaingroupApi + 'eq/app1/materiel/',//物料管理列表 (804)
    getMaterialEngineer_materielDetail: winchaingroupApi + 'eq/app1/materiel/',//物料详情 申请物料(805)
    createdMaterialEngineer_materiel: winchaingroupApi + 'eq/app1/materiel/',//申请物料创建(806)
    getMaterialEngineer_needmaterielList: winchaingroupApi + 'eq/app1/needmateriel/',//需采购物料列表(807)
    getMaterialEngineer_testallotList: winchaingroupApi + 'ex/app1/testallot/',//试验物料试验列表(809)
    getMaterialEngineer_testallotDetail: winchaingroupApi + 'ex/app1/testallot/',//试验物料试验列表(809)
    setMaterialEngineer_testallot: winchaingroupApi + 'ex/app1/testallot/',// 试验物料出借(811)
    getMaterialEngineer_maintainallotList: winchaingroupApi + 'eq/app1/maintainallot/',//维修物料维修列表(812)
    getMaterialEngineer_maintainallotDetail: winchaingroupApi + 'eq/app1/maintainallot/',//维修物料物料列表(813)
    setMaterialEngineer_maintainallot: winchaingroupApi + 'eq/app1/maintainallot/',//维修物料出借 (814)
    getMaterialEngineer_material_applicationList: winchaingroupApi + 'eq/app1/material_application/',//物料申请列表(808)
    getMaterialEngineer_testbackList: winchaingroupApi + 'ex/app1/testback/',//归还试验物料列表(815)
    getMaterialEngineer_testbackDetail: winchaingroupApi + 'ex/app1/testback/',//归还试验物料物料列表(816)
    setMaterialEngineer_testback: winchaingroupApi + 'ex/app1/testback/',//归还试验物料物料列表(817)
    getMaterialEngineer_maintainbackList: winchaingroupApi + 'eq/app1/maintainback/',//归还维修物料维修列表(818)
    getMaterialEngineer_maintainbackDetail: winchaingroupApi + 'eq/app1/maintainback/',//归还维修物料物料列表(819)
    setMaterialEngineer_maintainback: winchaingroupApi + 'eq/app1/maintainback/',//维修物料归还(820)
    getMaterialEngineer_verifyList: winchaingroupApi + 'ex/app1/verify/',//项目样件确认列表(801)
    getMaterialEngineer_verifyDetail: winchaingroupApi + 'ex/app1/verify/',// 项目样件详情(802)
    setMaterialEngineer_verify: winchaingroupApi + 'ex/app1/verify/',//项目样件确认(803)

    /**@name 设备计量员 */
    getGauger_systemNumber: winchaingroupApi + 'ex/app1/top6/',//数量统计(601)
    getGauger_outmeteringList: winchaingroupApi + 'eq/app1/outmetering/',//计量超时列表(612)
    getGauger_meqList: winchaingroupApi + 'eq/app1/meq/',//负责设备列表 (602)
    getGauger_meteringhistoryList: winchaingroupApi + 'eq/app1/meteringhistory/?equipment=',//设备计量列表(603)
    getGauger_meteringDetail: winchaingroupApi + 'eq/app1/metering/',//设备计量详情(606)
    getGauger_setHeaderDetail: winchaingroupApi + 'eq/app1/metering/',//计量进度(609)
    getGauger_reportMeasuring: winchaingroupApi + 'eq/app1/metering/',//计量报告详情(610)
    getGauger_meteringList: winchaingroupApi + 'eq/app1/metering/',// 30天设备计量列表(605)
    getGauger_meteringplanList: winchaingroupApi + 'eq/app1/meteringplan/',//计量进度列表(613)

    /**@name 设备工程师 */
    getEquipmentengineer_systemNumber: winchaingroupApi + 'ex/app1/top7/',//6hhh顶部数字统计 (708)
    getEquipmentengineer_maintainList: winchaingroupApi + 'eq/app1/maintain/',// 设备维修列表 (701)
    getEquipmentengineer_upkeepList: winchaingroupApi + 'eq/app1/upkeep/',//设备保养列表(703)
    getEquipmentengineer_manageList: winchaingroupApi + 'eq/app1/manage/',//负责设备列表 (704)
    getEquipmentengineer_safetyList: winchaingroupApi + 'eq/app1/safety/',//设备人员安全指导书列表(706)
    getEquipmentengineer_frockList: winchaingroupApi + 'eq/app1/frock/',//我的工装(705)
    getEquipmentengineer_operationList: winchaingroupApi + 'eq/v1/operation/',// 设备操作指导书列表(707)

    /**@name 试验工程师 */
    getTestengineer__systemNumber: winchaingroupApi + 'ex/app1/top5/',//顶部数字统计 (526)
    getTestengineer__finishexperimentList: winchaingroupApi + 'ex/app1/finishexperiment/',//已完成试验列表(510)
    getTestengineer__finishprojectList: winchaingroupApi + 'ex/app1/finishproject/',//已完成项目列表(511)
    getTestengineer__finishprojectDetail: winchaingroupApi + 'ex/app1/finishproject/',// 项目试验列表 (512)
    getTestengineer__myexperimentList: winchaingroupApi + 'ex/app1/myexperiment/',//试验列表(513)
    getTestengineer__myprojectList: winchaingroupApi + '/ex/app1/myproject/',//项目列表(515)
    getTestengineer__myprojectDetail: winchaingroupApi + 'ex/app1/myproject/',//项目验列表(516)
    getTestengineer__myexperimentFlow: winchaingroupApi + 'ex/v1/myexperiment/',// 试验流程(514)
    getTestengineer_exbomList: winchaingroupApi + 'ex/app1/exbom/?experiment=',// 试验物料列表 (517)
    getTestengineer_exeqrequiredList: winchaingroupApi + 'ex/app1/exeqrequired/?experiment=',// 试验设备清单(518)
    getTestengineer_exeqrequiredDetail: winchaingroupApi + 'ex/app1/exeqrequired/',//试验操作(520)
    createdTestengineer_exeq: winchaingroupApi + 'ex/app1/exeq/',//设备维修创建(519)
    getTestengineer_testersDetail: winchaingroupApi + 'ex/app1/testers/',// 试验实验员 (521)
    getTestengineer_testuserList: winchaingroupApi + 'users/app1/testuser/',//试验员列表(522)
    deleteTestengineer_testers: winchaingroupApi + 'ex/app1/testers/',//试验实验员删除(524)
    createdTestengineer_testers: winchaingroupApi + 'ex/app1/testers/',// 试验员安排(523)
    getTestengineer_alarmList: winchaingroupApi + 'eq/app1/alarm/',//新增报警列表(503)
    searchTestengineer_searcheqList: winchaingroupApi + 'eq/app1/searcheq/?search=',//新增报警设备搜索(501)
    createdTestengineer_alarm: winchaingroupApi + 'eq/app1/alarm/',//新增报警 创建 (502)
    getTestengineer_testwayList: winchaingroupApi + 'sys/app1/testway/',//试验方法列表(504)
    getTestengineer_ondutyList: winchaingroupApi + 'sys/app1/onduty/',//值班列表 (506)
    getTestengineer_roomList: winchaingroupApi + 'eq/app1/room/',// 实验室列表(509)
    /**@name 时间时分秒  */
    createdTestengineer_onduty: winchaingroupApi + 'sys/app1/onduty/',//值班申请创建(507)
    getTestengineer_ondutyingList: winchaingroupApi + 'sys/app1/ondutying/',//申请进度(508)
    getTestengineer_mytestwayList: winchaingroupApi + 'sys/app1/mytestway/',//我的试验方法列表(505)
    getTestengineer_cultivateList: winchaingroupApi + 'ex/app1/cultivate/',//培养人员(525)

    /**@name 实验室经理 */
    getTestManager_systemNumber: winchaingroupApi + 'ex/app1/top3/',//顶部数字统计(310)
    getTestManager_userList: winchaingroupApi + 'users/app1/user3/',//活跃人员(301)
    getTestManager_projectList: winchaingroupApi + 'ex/app1/project3/',//试验项目(305)
    getTestManager_standardList: winchaingroupApi + 'sys/app1/standard3/',//试验标准(302)
    getTestManager_eqList: winchaingroupApi + 'eq/app1/eq3/',//设备档案 (306)
    getTestManager_eqpctList: winchaingroupApi + 'eq/app1/eqpct/',//试验设备运行率(304)
    getTestManager_warehousepctList: winchaingroupApi + 'eq/app1/warehousepct/',//物料安全库存率(309)
    getTestManager_finishprojectList: winchaingroupApi + 'ex/app1/finishproject3/',//已完成项目 (307)
    getTestManager_finishprojectDetail: winchaingroupApi + 'ex/app1/finishproject3/',//项目试验(308)
    getTestManager_alertList: winchaingroupApi + 'eq/app1/alert/',//报警日志 (303)
    getTestManager_systemRate: winchaingroupApi + 'eq/app1/rate/',//设备维修保养率(311)

    /**@name 项目经理*/
    getProjectManage_systemNumber: winchaingroupApi + 'ex/app1/top4/',//顶部统计(411)
    getProjectManage_standardList: winchaingroupApi + 'sys/app1/standard4/',// 试验标准列表(403)
    getProjectManage_historyList: winchaingroupApi + 'ex/app1/finishproject4/',//项目历史列表 (401)
    getProjectManage_historyDetail: winchaingroupApi + 'ex/app1/finishproject4/',//项目试验详情(402)
    getProjectManage_projectList: winchaingroupApi + 'ex/app1/project/',//项目列表(404)
    deleteProjectManage_project: winchaingroupApi + 'ex/app1/project/',//项目删除(405)
    getProjectManage_experimentList: winchaingroupApi + 'ex/app1/experiment/?experiment_project=',//项目试验列表 (406)
    getProjectManage_appointList: winchaingroupApi + 'ex/app1/appoint/?experiment_project=',//项目试验预约列表(407)
    setProjectManage_appoint: winchaingroupApi + 'ex/v1/appoint/',//项目试验预约(408)
    getProjectManage_planList: winchaingroupApi + 'ex/app1/plan/?experiment_project=',// 项目试验进度列表(410)
    setProjectManage_appointinfo: winchaingroupApi + 'ex/v1/appointinfo/',//项目预约(412)

    /**@name 产品经理 */
    getProductManager_pruductpctFlow: winchaingroupApi + 'ex/app1/pruductpct/',//产品进度(201)
    getProductManager_myproductList: winchaingroupApi + 'ex/app1/myproduct/',// 负责产品(203)
    getProductManager_exfailList: winchaingroupApi + 'ex/app1/exfail/',//试验不合格列表(206)
    getProductManager_exfailDetail: winchaingroupApi + 'ex/app1/exfail/',//试验详情(207)
    setProduct_exfail: winchaingroupApi + 'ex/app1/exfail/',//  发送信息(208)
    getProductManager_produceList: winchaingroupApi + 'ex/app1/produce/',//产品列表(204)
    getProductManager_produceDetail: winchaingroupApi + 'ex/v1/flow/?product=',// 产品配置列表(205)
    getProductManager_projectpctFlow: winchaingroupApi + 'ex/v1/projectpct/?product=',//产品项目进度(212)
    getProductManager_expctList: winchaingroupApi + 'ex/v1/expct/?experiment_project=',//项目试验进度(213)
    getProductManager_expendList: winchaingroupApi + 'ex/app1/expend/',//产品支出(209)
    getProductManager_expendDetail: winchaingroupApi + 'ex/app1/expend/',// 项目支出(210)
    getProductManager_exexpendList: winchaingroupApi + 'ex/app1/exexpend/?experiment_project=',//试验支出(211)
    getProductManager_exexpendDetail: winchaingroupApi + 'ex/v1/exexpend/',//试验详情(215)
}
